[build]
publish = "packages/contented-example/.contented/out/"
command = "npm run build --workspace=@birthdayresearch/contented-processor && npm run generate --workspace=@birthdayresearch/contented-example"